#!/bin/bash

##########
function check-artefacts() {
   [ -d artefacts ] && {
      echo -n "found artefacts directory; sure you want to proceed ? (ctrl-c to quit) ? "
      read _
   }
}

######### 
coursedirs=""

function compute-coursedirs() {
   coursedirs=""
   for course in $courses; do
      coursedirs="$coursedirs $HOME/git/$course"
   done
}

function 5c-10s-2n {
   compute-coursedirs bioinfo mines-git-tuto mines-python-primer python3-s2 python-slides
   ./nbhtests.py -u 1-10 -i 1-2 $coursedirs "$@"
}

function 5c-20s-1n {
   compute-coursedirs bioinfo mines-git-tuto mines-python-primer python3-s2 python-slides
   ./nbhtests.py -u 1-20 -i 1 $coursedirs "$@"
}

# focus on this one:
# 50 w3/w3-s2-c3-for-sur-plusieurs-variables
function 1c-100s-1n {
   compute-coursedirs python3-s2 
   ./nbhtests.py -u 1-100 -i 50 $coursedirs "$@"
}

check-artefacts
"$@"
echo if all went well:
echo mv artefacts artefacts-$1