# Generated by Django 2.2.1 on 2019-06-11 08:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseDir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursename', models.CharField(max_length=128)),
                ('giturl', models.CharField(default='none', max_length=1024)),
                ('image', models.CharField(default='none', max_length=256)),
                ('autopull', models.BooleanField(default=False)),
                ('staff_usernames', models.TextField(blank=True, default='')),
                ('registered_users', models.ManyToManyField(related_name='courses_registered', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
