# Generated by Django 2.2.7 on 2020-07-30 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_registered_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedir',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
