# Generated by Django 3.1.7 on 2021-03-16 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_coursedir_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedir',
            name='autobuild',
            field=models.BooleanField(default=False),
        ),
    ]
