#!/bin/bash -x

function init() {

    docker stop flotbioinfo-x-john
    docker rm flotbioinfo-x-john

    nbh-del-student /nbhosting-test john
    nbh-add-student-in-course /nbhosting-test john flotbioinfo
}

function run() {
    run_line=$(run-student-course-jupyter /nbhosting-test john flotbioinfo w1/en-w1-e1-compute-gc-at.ipynb)

    echo line returned by run-student-course-jupyter : $run_line
    
    port=$(cut -d' ' -f2 <<< $run_line)
    token=$(cut -d' ' -f3 <<< $run_line)
    
    echo ++++++++++++++++++++ returned port $port
    echo ++++++++++++++++++++ returned token $token
    
    echo ++++++++++++++++++++ docker ps -a
    docker ps -a
    
    echo ++++++++++++++++++++ https
    curl -k https://localhost:$port/?token=$token
}

# force clean/init phase with the --init arg
[ "$1" == "init" ] && init
run



