#!/bin/bash
# -*- shell-script -*-
#
# nbhs = nbhosting status
# a developer tool for getting an overview of what's going on
#

root=/nbhosting

function status-users() {
    echo "--- USERS in passwd"
    grep '^[^:]*:[^:]*:[0-9][0-9][0-9][0-9]' /etc/passwd | grep -v '^nfsnobody'
    echo "--- USERS in group"
    grep '^[^:]*:[^:]*:[0-9][0-9][0-9][0-9]' /etc/group | egrep -v '^(nfsnobody|docker)'
}

function list-tree() {
    find $root -type d | fgrep -v '/.git/'
}

function status-tree() {
    echo "--- courses in $root/courses-git"
    ls $root/courses-git
    echo "--- courses in $root/courses"
    ls $root/courses
    echo "--- students in $root"
    ls $root/students
}

function status-docker() {
    echo "--- all docker containers"
    docker ps -a
    echo "--- running docker containers"
    docker ps
}

function status() {
#    list-tree
    status-tree
    status-users
    status-docker
}

function clear-docker-light() {
    containers=$(docker ps --format '{{.Names}}')
    for c in $containers; do
	echo "Killing $c"
	docker kill $c
    done
}

function clear-docker-deep() {
    containers=$(docker ps -a --format '{{.Names}}')
    for c in $containers; do
	echo "Removing $c"
	docker rm $c
    done
}

function clear-users() {
    for userdir in $(ls -d /nbhosting/students/* 2>/dev/null); do
	user=$(basename $userdir)
	echo deleting user $user
	nbh-del-student /nbhosting $user
    done
}

function clear-logs() {
    for file in /var/log/nginx/daemon $(find /nbhosting/logs -name '*.log' 2> /dev/null); do
	echo clearing log file $file
	echo ==================== > $file
    done
}

function clear() {
    clear-docker-light
    clear-docker-deep
    clear-users
    clear-logs
}

function clear-light() {
    clear-docker-light
}

# if args are provided, take this as a call to a local function
# e.g. meta status-tree => status-tree
# or call just status by default
[[ -z "$@" ]] && status || "$@"

