#!/usr/bin/env bash

shopt -s globstar

NBHROOT=${NBHROOT:=/nbhosting/current}

[ -d "${NBHROOT}" ] || {
    echo "WARNING : NBHROOT=${NBHROOT} - not found - exiting"
    exit 1
}

[ -d ${NBHROOT}/local ] || {
    echo "no change - dir ${NBHROOT}/local not found"
    exit 0
}

echo ============================== local config

cd ${NBHROOT}/local

if [ -z "$@" ]; then
    courses="*"
else
    courses="$@"
fi

function show-locals-for-course() {
    local course="$1"; shift
    pushd $course >& /dev/null
    echo ==================== course $course
    for file in **/*; do
        local official="${NBHROOT}/courses-git/$course/.nbhosting/$file"
        local localfile="$(pwd)/$file"
        if [[ "$file" == "Dockerfile" ]]; then
            if [[ ! -f "$official" ]]; then
                echo ========== cat $localfile
                cat $file
            else
                echo "========== diff (fromgit) <-> $localfile"
                diff $official $localfile
            fi
        elif [[ "$file" =~ .*~ ]]; then
            continue
        else
            echo ========== cat $localfile
            cat $localfile
        fi
    done
    popd &> /dev/null
}

for course in $courses; do
    show-locals-for-course $course
done
