#!/bin/bash
# -*- mode: shell-script -*-

# delete login name <student> and all his homedir

COMMAND=$(basename $0)
USAGE="Usage: $COMMAND nbhosting-root student" 

[ "$#" -eq 2 ] || { echo $USAGE; exit 1; }

# from config - typically /nbhosting
root=$1; shift
# the unix login name
student=$1; shift

userdel --remove --force $student
