#!/bin/bash

shopt -s globstar

[ -d /nbhosting/current ] || {
    echo "WARNING : using hard-wired NBHROOT=/nbhosting/current - not found - exiting"
    exit 1
}

[ -d /nbhosting/current/local ] || {
    echo "no change - dir /nbhosting/current/local not found"
    exit 0
}

echo ============================== local config

cd /nbhosting/current/local

if [ -z "$@" ]; then
    courses="*"
else
    courses="$@"
fi

function show-locals-for-course() {
    local course="$1"; shift
    pushd $course >& /dev/null
    echo ==================== course $course
    for file in **/*; do
        local official="/nbhosting/current/courses-git/$course/.nbhosting/$file"
        local localfile="$(pwd)/$file"
        if [[ "$file" == "Dockerfile" ]]; then
            if [[ ! -f "$official" ]]; then
                echo ========== cat $localfile
                cat $file
            else
                echo "========== diff (fromgit) <-> $localfile"
                diff  $file
            fi
        elif [[ "$file" =~ .*~ ]]; then
            continue
        else
            echo ========== cat $localfile
            cat $localfile
        fi
    done
    popd &> /dev/null
}

for course in $courses; do
    show-locals-for-course $course
done

    
