#!/usr/bin/env python3

# pylint: disable=c0111

from argparse import ArgumentParser, ArgumentDefaultsHelpFormatter

from nbhosting.stats.monitor import Monitor

def main():
    parser = ArgumentParser(formatter_class=ArgumentDefaultsHelpFormatter)
    # default was 2 hours with the jupyter-v4 strategy,
    # which was based on the last time a notebook was opened
    # with jupyter-v5 we can now really apply a timeout
    parser.add_argument(
        "-p", "--period", default=15, type=int,
        help="monitor period in minutes - how often are checks performed")
    parser.add_argument(
        "-i", "--idle", default=30, type=int, dest='idle',
        help="timeout in minutes - kill containers idle more than that")
    parser.add_argument(
        "-u", "--unused", default=15, type=int, dest='unused',
        help="timeout in days - remove containers unused more than that")
    parser.add_argument(
        "-d", "--debug", action='store_true', default=False)

    args = parser.parse_args()
    Monitor(
        period=60 * args.period,
        idle=60 * args.idle,
        unused=24*3600 * args.unused,
        debug=args.debug).run_forever()


if __name__ == '__main__':
    main()
