all: flotbioinfo flotpython datasciencehandbook

flotbioinfo:
	docker build -f flotbioinfo.Dockerfile -t flotbioinfo .

flotpython:
	docker build -f flotpython.Dockerfile -t flotpython .

datasciencehandbook:
	docker build -f datasciencehandbook.Dockerfile -t datasciencehandbook .
